name: Validate Documentation Pages

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  validate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Validate documentation pages
        run: pnpm run validate-docs
